// src/templates.js

export const templates = {
  classic: {
    id: 'classic',
    name: 'Classic Elegance',
    description: 'Timeless design with sophisticated typography and subtle animations.',
    tags: ['Elegant', 'Timeless'],
    preview: 'bg-gradient-to-br from-slate-50 to-indigo-100',
    previewCard: 'bg-white/80 backdrop-blur-sm border border-slate-200/50 shadow-lg',
    previewAccent: 'bg-blue-300',
    tagStyle: 'bg-blue-100 text-blue-800',
    tagStyle2: 'bg-slate-100 text-slate-800',
    mainBg: 'bg-gray-100',
    headerStyle: 'bg-gradient-to-r from-blue-600 to-indigo-700 text-white',
    iconBg: 'bg-white',
    cardStyle: 'bg-white border border-gray-200',
    accent: 'border-l-4 border-blue-500',
    textStyle: 'text-gray-900'
  },
  neon: {
    id: 'neon',
    name: 'Neon Cyber',
    description: 'Futuristic cyberpunk aesthetic with glowing neon accents.',
    tags: ['Cyberpunk', 'Futuristic'],
    preview: 'bg-gradient-to-br from-gray-900 via-purple-900 to-black',
    previewCard: 'bg-black/50 backdrop-blur-sm border border-cyan-500/30 shadow-lg',
    previewAccent: 'bg-cyan-400',
    tagStyle: 'bg-cyan-100 text-cyan-800',
    tagStyle2: 'bg-purple-100 text-purple-800',
    mainBg: 'bg-gray-900',
    headerStyle: 'bg-gradient-to-r from-purple-900 via-cyan-500 to-black text-white',
    iconBg: 'bg-gray-800',
    cardStyle: 'bg-gray-800 border border-cyan-500',
    accent: 'border-l-4 border-cyan-500',
    textStyle: 'text-white'
  },
  nature: {
    id: 'nature',
    name: 'Organic Nature',
    description: 'Earth-inspired design with natural textures and green tones.',
    tags: ['Organic', 'Natural'],
    preview: 'bg-gradient-to-br from-green-100 via-emerald-50 to-teal-100',
    previewCard: 'bg-green-50/80 backdrop-blur-sm border border-green-200/50 shadow-lg',
    previewAccent: 'bg-green-400',
    tagStyle: 'bg-green-100 text-green-800',
    tagStyle2: 'bg-emerald-100 text-emerald-800',
    mainBg: 'bg-green-50',
    headerStyle: 'bg-gradient-to-r from-green-600 to-emerald-700 text-white',
    iconBg: 'bg-green-100',
    cardStyle: 'bg-white border border-green-200',
    accent: 'border-l-4 border-green-500',
    textStyle: 'text-gray-900'
  },
  retro: {
    id: 'retro',
    name: 'Retro Wave',
    description: '80s synthwave vibes with bold gradients and vintage aesthetics.',
    tags: ['80s Vibe', 'Synthwave'],
    preview: 'bg-gradient-to-br from-pink-400 via-purple-500 to-indigo-600',
    previewCard: 'bg-indigo-900/50 backdrop-blur-sm border border-pink-300/30 shadow-lg',
    previewAccent: 'bg-pink-400',
    tagStyle: 'bg-pink-100 text-pink-800',
    tagStyle2: 'bg-purple-100 text-purple-800',
    mainBg: 'bg-purple-100',
    headerStyle: 'bg-gradient-to-r from-pink-500 via-purple-600 to-indigo-700 text-white',
    iconBg: 'bg-purple-100',
    cardStyle: 'bg-white border border-purple-300',
    accent: 'border-l-4 border-pink-500',
    textStyle: 'text-gray-900'
  },
  minimalist: {
    id: 'minimalist',
    name: 'Pure Minimal',
    description: 'Clean, minimal design focused on content and whitespace.',
    tags: ['Clean', 'Simple'],
    preview: 'bg-white',
    previewCard: 'bg-white border border-gray-200 shadow-lg',
    previewAccent: 'bg-gray-800',
    tagStyle: 'bg-gray-100 text-gray-800',
    tagStyle2: 'bg-slate-100 text-slate-800',
    mainBg: 'bg-white',
    headerStyle: 'bg-gray-100 text-gray-900',
    iconBg: 'bg-gray-50',
    cardStyle: 'bg-white border border-gray-200',
    accent: 'border-l-4 border-gray-400',
    textStyle: 'text-gray-900'
  },
  galaxy: {
    id: 'galaxy',
    name: 'Cosmic Galaxy',
    description: 'Space-themed design with stellar gradients and cosmic effects.',
    tags: ['Cosmic', 'Stellar'],
    preview: 'bg-gradient-to-br from-indigo-900 via-purple-800 to-black',
    previewCard: 'bg-black/50 backdrop-blur-sm border border-purple-400/30 shadow-lg',
    previewAccent: 'bg-purple-400',
    tagStyle: 'bg-indigo-100 text-indigo-800',
    tagStyle2: 'bg-purple-100 text-purple-800',
    mainBg: 'bg-indigo-950',
    headerStyle: 'bg-gradient-to-r from-indigo-900 via-purple-800 to-black text-white',
    iconBg: 'bg-indigo-900',
    cardStyle: 'bg-indigo-900 border border-purple-500',
    accent: 'border-l-4 border-purple-500',
    textStyle: 'text-white'
  },
  sunset: {
    id: 'sunset',
    name: 'Golden Sunset',
    description: 'Warm sunset colors with golden accents and soft transitions.',
    tags: ['Warm', 'Golden'],
    preview: 'bg-gradient-to-br from-yellow-200 via-orange-300 to-red-400',
    previewCard: 'bg-orange-50/80 backdrop-blur-sm border border-orange-200/50 shadow-lg',
    previewAccent: 'bg-orange-400',
    tagStyle: 'bg-orange-100 text-orange-800',
    tagStyle2: 'bg-yellow-100 text-yellow-800',
    mainBg: 'bg-orange-50',
    headerStyle: 'bg-gradient-to-r from-orange-500 via-red-500 to-yellow-500 text-white',
    iconBg: 'bg-orange-100',
    cardStyle: 'bg-white border border-orange-300',
    accent: 'border-l-4 border-orange-500',
    textStyle: 'text-gray-900'
  },
  arctic: {
    id: 'arctic',
    name: 'Arctic Ice',
    description: 'Cool, icy design with crystalline effects and frosty tones.',
    tags: ['Cool', 'Icy'],
    preview: 'bg-gradient-to-br from-blue-100 via-cyan-50 to-white',
    previewCard: 'bg-blue-50/70 backdrop-blur-sm border border-blue-200/60 shadow-lg',
    previewAccent: 'bg-cyan-400',
    tagStyle: 'bg-blue-100 text-blue-800',
    tagStyle2: 'bg-cyan-100 text-cyan-800',
    mainBg: 'bg-blue-50',
    headerStyle: 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white',
    iconBg: 'bg-blue-100',
    cardStyle: 'bg-white border border-blue-300',
    accent: 'border-l-4 border-blue-500',
    textStyle: 'text-gray-900'
  }
};
